<?php

use Illuminate\Database\Seeder;

class VideoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('videos')->insert([
            [
                'id' => 1,
                'category_id' => 1,
                'title' => '【初級】保険について勉強しよう1',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => '保険について説明します。',
                'content' => 'まず保険の歴史や役割について解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 2,
                'category_id' => 1,
                'title' => '【初級】保険について勉強しよう2',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => '保険商品について説明します。',
                'content' => '保険商品の代表例について解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 3,
                'category_id' => 2,
                'title' => '【初級】保険について勉強しよう3',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => 'それぞれの保険商品のメリットについて説明します。',
                'content' => 'それぞれの保険商品のメリットについて解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 4,
                'category_id' => 4,
                'title' => '【初級】保険について勉強しよう4',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => '保険について説明します。',
                'content' => 'まず保険の歴史や役割について解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 5,
                'category_id' => 1,
                'title' => '【初級】保険について勉強しよう5',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => '保険商品について説明します。',
                'content' => '保険商品の代表例について解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 6,
                'category_id' => 1,
                'title' => '【初級】保険について勉強しよう6',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => 'それぞれの保険商品のメリットについて説明します。',
                'content' => 'それぞれの保険商品のメリットについて解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 7,
                'category_id' => 1,
                'title' => '【初級】保険について勉強しよう7',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => '保険について説明します。',
                'content' => 'まず保険の歴史や役割について解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 8,
                'category_id' => 1,
                'title' => '【初級】保険について勉強しよう8',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => '保険商品について説明します。',
                'content' => '保険商品の代表例について解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 9,
                'category_id' => 1,
                'title' => '【初級】保険について勉強しよう9',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => 'それぞれの保険商品のメリットについて説明します。',
                'content' => 'それぞれの保険商品のメリットについて解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 10,
                'category_id' => 1,
                'title' => '【初級】保険について勉強しよう9',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => 'それぞれの保険商品のメリットについて説明します。',
                'content' => 'それぞれの保険商品のメリットについて解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 11,
                'category_id' => 1,
                'title' => '【中級】保険について勉強しよう1',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => '保険について説明します。',
                'content' => 'まず保険の歴史や役割について解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 12,
                'category_id' => 1,
                'title' => '【中級】保険について勉強しよう2',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => '保険商品について説明します。',
                'content' => '保険商品の代表例について解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 13,
                'category_id' => 2,
                'title' => '【中級】保険について勉強しよう3',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => 'それぞれの保険商品のメリットについて説明します。',
                'content' => 'それぞれの保険商品のメリットについて解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 14,
                'category_id' => 4,
                'title' => '【中級】保険について勉強しよう4',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => '保険について説明します。',
                'content' => 'まず保険の歴史や役割について解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 15,
                'category_id' => 1,
                'title' => '【中級】保険について勉強しよう5',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => '保険商品について説明します。',
                'content' => '保険商品の代表例について解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 16,
                'category_id' => 1,
                'title' => '【中級】保険について勉強しよう6',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => 'それぞれの保険商品のメリットについて説明します。',
                'content' => 'それぞれの保険商品のメリットについて解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 17,
                'category_id' => 1,
                'title' => '【中級】保険について勉強しよう7',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => '保険について説明します。',
                'content' => 'まず保険の歴史や役割について解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 18,
                'category_id' => 1,
                'title' => '【中級】保険について勉強しよう8',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => '保険商品について説明します。',
                'content' => '保険商品の代表例について解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 19,
                'category_id' => 1,
                'title' => '【中級】保険について勉強しよう9',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => 'それぞれの保険商品のメリットについて説明します。',
                'content' => 'それぞれの保険商品のメリットについて解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 20,
                'category_id' => 1,
                'title' => '【中級】保険について勉強しよう9',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => 'それぞれの保険商品のメリットについて説明します。',
                'content' => 'それぞれの保険商品のメリットについて解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 21,
                'category_id' => 1,
                'title' => '【上級】保険について勉強しよう1',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => '保険について説明します。',
                'content' => 'まず保険の歴史や役割について解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 22,
                'category_id' => 1,
                'title' => '【上級】保険について勉強しよう2',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => '保険商品について説明します。',
                'content' => '保険商品の代表例について解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 23,
                'category_id' => 2,
                'title' => '【上級】保険について勉強しよう3',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => 'それぞれの保険商品のメリットについて説明します。',
                'content' => 'それぞれの保険商品のメリットについて解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 24,
                'category_id' => 4,
                'title' => '【上級】保険について勉強しよう4',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => '保険について説明します。',
                'content' => 'まず保険の歴史や役割について解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 25,
                'category_id' => 1,
                'title' => '【上級】保険について勉強しよう5',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => '保険商品について説明します。',
                'content' => '保険商品の代表例について解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 26,
                'category_id' => 1,
                'title' => '【上級】保険について勉強しよう6',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => 'それぞれの保険商品のメリットについて説明します。',
                'content' => 'それぞれの保険商品のメリットについて解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 27,
                'category_id' => 1,
                'title' => '【上級】保険について勉強しよう7',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => '保険について説明します。',
                'content' => 'まず保険の歴史や役割について解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 28,
                'category_id' => 1,
                'title' => '【上級】保険について勉強しよう8',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => '保険商品について説明します。',
                'content' => '保険商品の代表例について解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 29,
                'category_id' => 1,
                'title' => '【上級】保険について勉強しよう9',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => 'それぞれの保険商品のメリットについて説明します。',
                'content' => 'それぞれの保険商品のメリットについて解説します。',
                'author' => '山田義昭',
            ],
            [
                'id' => 30,
                'category_id' => 1,
                'title' => '【上級】保険について勉強しよう9',
                'video_url' => 502084279,
                'image_src' => '',
                'detail' => 'それぞれの保険商品のメリットについて説明します。',
                'content' => 'それぞれの保険商品のメリットについて解説します。',
                'author' => '山田義昭',
            ],
        ]);
    }
}
